In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
df= pd.read_csv('../data/gurgaon_properties.csv')

In [5]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1337,4 BHK Flat in Sector 78 Gurgaon,flat,umang monsoon breeze,1.25,5000.0,2500.0,Super Built up area 2350(218.32 sq.m.)Built Up...,4,4,3,"servant room,others,pooja room","G201, Sector 78 Gurgaon, Gurgaon, Haryana",2.0,East,1 to 5 Year Old,"['Proposed Metro Station', 'Mahapal Shing', 'N...","Corner 4 bhk / 4 baths/ 1 setvant room, road f...","['1 Water Purifier', 'No AC', 'No Bed', 'No Ch...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3635,2 BHK Flat in Sector 104 Gurgaon,flat,puri emerald bay,1.59,10903.0,1458.0,Super Built up area 1550(144 sq.m.),2,2,2,not available,"B1,b2 ,b3, Sector 104 Gurgaon, Gurgaon, Haryana",12.0,South,1 to 5 Year Old,"['Sector-21 Metro Dwarka', 'Gurgaon Dreamz Mal...","All sculpture are imported from bali, indonesi...","['3 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of..."
2560,4 Bedroom House for sale in DLF Phase 1,house,independent,4.00,29630.0,1350.0,Plot area 150(125.42 sq.m.),4,4,3,store room,"DLF Phase 1, Gurgaon, Haryana",2.0,North,10+ Year Old,"['Guru dronacharya metro station', 'Dlf phase ...",150 sqyd villa available for sale in dlf phase...,"['3 Fan', '6 Light', 'No AC', 'No Bed', 'No Ch...","['Private Garden / Terrace', 'Water Storage', ...","['Environment5 out of 5', 'Safety5 out of 5', ..."
1276,3 BHK Flat in Sector 54 Gurgaon,flat,dlf the grove,5.70,41245.0,1382.0,Built Up area: 1382 (128.39 sq.m.),3,3,3,not available,"Sector 54, Sector 54 Gurgaon, Gurgaon, Haryana",1.0,East,undefined,"['Sector 54 chowk metro station', 'Sector 53-5...",3bhk multistorey apartment for resale in dlf t...,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
2901,3 BHK Flat in Sector 37D Gurgaon,flat,ramprastha the edge towers,1.00,5649.0,1770.0,Super Built up area 1770(164.44 sq.m.),3,3,3+,not available,"Sector 37D Gurgaon, Gurgaon, Haryana",13.0,NaN,5 to 10 Year Old,"['MDS Public School', 'St Pauls School', 'Sunc...",It semi- Furnished wardrobes and modular kitchen,[],"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area4 out of 5', 'Construction4 out of..."

In [6]:
df.shape

(3961, 20)

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3961 entries, 0 to 3960
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3961 non-null   object
 1   property_type    3961 non-null   object
 2   society          3960 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3961 non-null   object
 7   bedRoom          3961 non-null   int64
 8   bathroom         3961 non-null   int64
 9   balcony          3961 non-null   object
 10  additionalRoom   3961 non-null   object
 11  address          3950 non-null   object
 12  floorNum         3940 non-null   float64
 13  facing           2784 non-null   object
 14  agePossession    3960 non-null   object
 15  nearbyLocations  3754 non-null   object
 16  description      3961 non-null   object
 17  furnishDetails   2929 non-null   object
 18  features         3252 non-null   object
 19  rating           3511 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 619.0+ KB

In [9]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                20
price_per_sqft       20
area                 20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
dtype: int64

In [13]:
df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon', '').str.strip()

0                                               Sector 90
1                                                   Sohna
2                                              Sector 70A
3                                         Sector-33 Sohna
4                                               Sector 92
5                                              Sector 109
6                                                   Sohna
7                                              Sohna Road
8                                               Sector 81
9                                              Sector 102
10                                             Sector 17A
11                                              Sector 84
12                                              Sector 63
13                                              Sector 77
14                                               Sector 4
15                                              Sector 85
16                                              Sector 67
17                                              Sector 61
18                                              Sector 69
19                                             Sector 70A
20                                        Nirvana Country
21                                              Sector 72
22                                              Sector 92
23                                              Sector 69
24                                              Sector 85
25                                              Sector 95
26                                              Sector 22
27                                              Sector 54
28                                              Sector 56
29                                             Sector 107
30                                              Sector 56
31                                              Sector 85
32                                             South City
33                                        Nirvana Country
34                                             Sector 111
35                                             Sector 109
36                                              Sector 40
37                                             Sector 37C
38                                             Sector 17B
39                                             Sector 99A
40                                              Sector 81
41                                              Sector 68
42                                            DLF Phase 2
43                                              Sector 62
44                                              Sector 63
45                                               Sector 4
46                                              Sector 92
47                                              Sector 70
48                                             Sector 106
49                                             Sector 107
50                                          Dharam Colony
51                                              Sector 81
52                                        Nirvana Country
53                                        Sector-33 Sohna
54                                                  Sohna
55                                             Sector 37D
56                                           Baldev Nagar
57                                              Sector 82
58                                              Sector 74
59                                              Sector 90
60                                              Sector 85
61                                        Sector-33 Sohna
62                                              Sector 50
63                                              Sector 71
64                                              Sector 66
65                                              Sector 60
66                                             Sector 104
67                                              Sector 62
68                                              Sector 92
69                                              Sector 77
70                                              Sector 83
71                                             Sector 107
72                                             Sector 109
73                                   Sector 1 Imt Manesar
74                                    Sushant Lok Phase 3
75                                           Sispal Vihar
76                                              Sector 69
77                                              Sector 61
78                                             Sector 104
79                                             Sector 107
80                                              Sector 83
81                                              Sector 72
82                                             Sector 37D
83                                              Sector 86
84                                             Sector 103
85                                              Sector 46
86                                           Laxman Vihar
87                                            Palam Vihar
88                                              Sector 83
89                                              Sector 70
90                                              Sector 77
91                          Ashok Vihar Phase 3 Extension
92                                             Sector 106
93                                              Sector 90
94                                                  Sohna
95                                             Sector 63A
96                                          Rattan Garden
97                                             Sector 102
98                                              Sector 49
99                                    Sushant Lok Phase 2
100                                             Sector 52
101                                             Sector 86
102                                            Sector 113
103                                           DLF Phase 1
104                                             Sector 92
105                                           Ashok Vihar
106                                             Sector 92
107                                             Sector 72
108                                              Sector 7
109                                            Sector 103
110                                             Sector 59
111                                             Sector 65
112                                           DLF Phase 4
113                                             Sector 85
114                                             Sector 81
115                                             Sector 83
116                                            Sector 106
117                                  Laxman Vihar Phase 2
118                                             Sector 46
119                                             Sector 81
120                                             Sector 62
121                                             Sector 81
122                                                 Sohna
123                                             Sector 33
124                                             Sector 92
125                                       Nirvana Country
126                                             Sector 65
127                                            Sector 10A
128                                            Sector 106
129                                       Sector-33 Sohna
130                                       Dayanand Colony
131                                             Sector 65
132                                       Sector-33 Sohna
133                                       Uppals Southend
134                                            Sector 37D
135                                            Sector 112
136                                             Sector 86
137                                            Sector 82A
138                                        Greenwood City
139                                             Sector 89
140                                            Sector 67A
141                                             Sector 90
142                                             Sector 85
143                                            Sector 108
144                                            Sector 109
145                                             Sector 54
146                                             Sector 69
147                                             Sector 90
148                                            Sector 109
149                                             Sector 22
150                                           Gwal Pahari
151                                        Devilal Colony
152                                            Sector 106
153                                            Sector 110
154                                             Sector 81
155                                             Sector 67
156                                            Sector 88A
157                                             Sector 92
158                                         Rajendra Park
159                                                 Sohna
160                                            Sector 99A
161                                            Sector 82A
162                                             Sector 66
163                                             Sector 62
164                                             Sector 82
165                                             Sector 95
166                                            Sector 37C
167                                             Sector 89
168                                            Sector 103
169                                      West Rajiv Nagar
170                                   Sushant Lok Phase 1
171                                                 Sohna
172                                       Sector-33 Sohna
173                                             Sector 90
174                                           Palam Vihar
175                                             Sector 65
176                                           DLF Phase 5
177                                             Sector 92
178                                             Sector 83
179                                          South City 1
180                                             Sector 21
181                                           DLF Phase 1
182                                           Sushant Lok
183                                             Sector 95
184                                             Sector 70
185                                             Sector 39
186                                            Sector 104
187                                            Sector 63A
188                                             Sector 45
189                                             Sector 11
190                                             Sector 92
191                                             Sector 72
192                                             Sector 69
193                                         Garhi Harsaru
194                                           DLF Phase 3
195                                                 Sohna
196                                                 Sohna
197                                             Sector 95
198                                           Malibu Town
199                                             Sector 66
200                                             Sector 66
201                                             Sector 68
202                                             Sector 14
203                                             Sector 66
204                                             Sector 69
205                                            Sector 37C
206                                             Sector 48
207                                             Sector 95
208                                             Sector 48
209                                            Cyber City
210                                                 Sohna
211                                             Sector 85
212                                         Rajendra Park
213                                             Sector 83
214                                             Sector 22
215                                             Sector 83
216                                             Sector 79
217                                   Sushant Lok Phase 3
218                                             Sector 65
219                                            Sector 70A
220                                             Sector 48
221                                           Mohan Nagar
222                                             Vir Nagar
223                                        Krishna Colony
224                                            Sector 104
225                                              Sector 5
226                                              Sector 3
227                                             Sector 84
228                                             Sector 83
229                                   Sushant Lok Phase 1
230                                             Sector 52
231                                          Mahavir pura
232                                             Sector 69
233                                         Heritage City
234                                       Nirvana Country
235                                             Sector 85
236                                             Sector 92
237                                             Sector 72
238                                             Sector 85
239                                            Sector 99A
240                                                Kanahi
241                                            Sector 37D
242                                            Sector 37D
243                                            Sector 104
244                                 Sector 1A IMT Manesar
245                                             Sector 90
246                                             Sector 84
247                                            Sector 37D
248                                             Sector 86
249                                           Palam Vihar
250                                                 Sohna
251                                             Sector 66
252                                            Sector 70A
253                                             Sector 49
254                                             Sector 70
255                                           Gwal Pahari
256                                             Sector 68
257                                            Sector 109
258                                       Sector-33 Sohna
259                                               Suncity
260                                  HUDA Saraswati Vihar
261                                              Rosewood
262                                             Sector 15
263                                        Devilal Colony
264                                             Sector 33
265                                       Sector-33 Sohna
266                                         Rajendra Park
267                                                 Sohna
268                                            Sector 113
269                                             Sector 84
270                                             Sector 67
271                                  Sector 1 Imt Manesar
272                                             Sector 68
273                                             Sector 90
274                                             Sector 31
275                                             Sector 56
276                                             Sector 84
277                                             Sector 93
278                                             Sector 65
279                                             Sector 81
280                                             Sector 46
281                                             Sector 83
282                                             Sector 83
283                                                  Nars
284                                            Sector 37D
285                                             Sector 95
286                                             Sector 85
287                                             Sector 70
288                                             Sector 90
289                                             Sector 81
290                                            Sector 110
291                                             Sector 49
292                                             Sector 41
293                                             Sector 65
294                                             Sector 90
295                                             Sector 79
296                                             Sector 48
297                                            Sector 37D
298                                             Sector 99
299                                             Sector 72
300                                             Sector 90
301                                             Sector 40
302                                            Sector 70A
303                                            Ravi Nagar
304                                             Sector 79
305                                            Sector 102
306                                             Sector 70
307                                             Sector 82
308                                             Sector 15
309                                         Garhi Harsaru
310                                            Sector 106
311                                             Sector 82
312                                             Sector 78
313                                             Sector 92
314                                             Sector 81
315                                             Sector 91
316                                       Nirvana Country
317                                             Sector 53
318                                            Sector 37D
319                                           DLF Phase 1
320                                             Sector 85
321                                             Sector 78
322                                                 Kheri
323                                             Sector 79
324                                             Sector 72
325                                            Sector 37D
326                                           Malibu Town
327                                            Sector 103
328                                   Sushant Lok Phase 1
329                                             Sector 92
330                                             Sector 79
331                                            Sector 102
332                                          Pratap Nagar
333                                           DLF Phase 1
334                                         Surat Nagar 1
335                                             Sector 70
336                                             Sector 48
337                                             Sector 69
338                                             Sector 43
339                                            Sector 37C
340                                            Sector 104
341                                             Sector 83
342                                            Sector 113
343                                             Sector 69

In [14]:
df.insert(loc=3, column='sector', value= df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon', '').str.strip())

In [15]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 90 Gurgaon,flat,shree vardhman flora,Sector 90,0.85,4404.0,1930.0,Super Built up area 1930(179.3 sq.m.)Carpet ar...,3,4,3,"servant room,store room","305, Sector 90 Gurgaon, Gurgaon, Haryana",3.0,South-East,1 to 5 Year Old,"['IRIS Broadway Mall', 'Dwarka Expressway', 'S...",One of the best location of the society with g...,NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction5 out of..."
1,2 BHK Flat in Sohna,flat,gls arawali homes,Sohna,0.27,4600.0,587.0,Super Built up area 576(53.51 sq.m.),2,2,2,not available,"Sohna, Gurgaon, Haryana",5.0,NaN,0 to 1 Year Old,"['Huda City Centre', 'Golf Course Road', 'Delh...",Tower 13 floor 5th house no. 508. Freehold pro...,[],"['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Management4 out of 5', 'Green Area5 out of 5..."
2,2 Bedroom House for sale in Sector 70A Gurgaon,house,bptp pedestal,Sector 70A,0.90,7582.0,1187.0,Carpet area: 1187 (110.28 sq.m.),2,2,3+,"servant room,others","123, Sector 70A Gurgaon, Gurgaon, Haryana",3.0,North-East,0 to 1 Year Old,"['Ninex Mall', 'Airia Mall', 'Meditree Market'...",This 2 bhk house for sale in sector 70a gurgao...,"['1 Exhaust Fan', '3 AC', '1 Modular Kitchen',...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Safety4 out of 5', ..."
3,4 BHK Flat in Sector-33 Sohna,flat,central park flower valley,Sector-33 Sohna,2.30,12777.0,1800.0,Carpet area: 1800 (167.23 sq.m.),4,4,3+,"pooja room,servant room","Sector-33 Sohna, Gurgaon, Haryana",5.0,North-East,0 to 1 Year Old,"['Golf Course Extension Rd', 'Rajiv Chowk - So...",9 sports academiesMulti-Cuisine restaurantKids...,"['4 Wardrobe', '4 Fan', '18 Light', '1 Chimney...","['Feng Shui / Vaastu Compliant', 'Security / F...",NaN
4,3 BHK Flat in Sector 92 Gurgaon,flat,sare crescent parc,Sector 92,0.51,4080.0,1250.0,Super Built up area 1250(116.13 sq.m.),3,2,2,not available,"Sare, Sector 92 Gurgaon, Gurgaon, Haryana",2.0,North,1 to 5 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",Ready to move in keys in hand for visit feel f...,[],"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area4 out of 5', 'Construction4 out of..."

In [16]:
df['sector'] = df['sector'].str.lower()

In [17]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 81                                                     90
sector 90                                                     90
sector 65                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 95                                                     57
sector 56                                                     57
sector 89                                                     56
sector 48                                                     56
sector 70a                                                    54
nirvana country                                               53
sector 70                                                     53
sector 37c                                                    53
sector 84                                                     51
sector-33 sohna                                               51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
sector 113                                                    43
dlf phase 2                                                   43
dlf phase 1                                                   43
sector 61                                                     42
sector 82                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 72                                                     29
sector 77                                                     29
sector 54                                                     27
sector 71                                                     27
laxman vihar                                                  27
dlf phase 4                                                   26
sector 112                                                    24
sector 88a                                                    23
sector 33                                                     23
dlf phase 3                                                   22
sector 67a                                                    22
sector 111                                                    22
sector 22                                                     20
sector 82a                                                    20
sector 78                                                     19
sector 74                                                     18
sector 63a                                                    18
sector 91                                                     17
sector 62                                                     17
sector 99                                                     16
sector 110                                                    16
sushant lok phase 3                                           16
sector 63                                                     15
sector 14                                                     15
sector 60                                                     15
sector 52                                                     14
sector 1 imt manesar                                          14
dlf phase 5                                                   14
gwal pahari                                                   14
rajendra park                                                 14
sector 53                                                     14
sector 3                                                      14
sector 76                                                     14
laxman vihar phase 2                                          13
sector 46                                                     13
sector 36a                                                    13
uppals southend                                               12
sector 39                                                     12
sector 50                                                     12
sector 93                                                     12
sector 31                                                     12
sector 38                                                     12
sohna road                                                    12
sector 47                                                     11
sector 9a                                                     11
ashok vihar phase 3 extension                                 11
sector 1a imt manesar                                         10
sector 7                                                      10
sector 4                                                       9
sector 55                                                      9
sector 95a                                                     9
south city 1                                                   9
ashok vihar phase 2                                            9
dwarka expressway                                              8
c block sushant lok phase 1                                    8
sector 40                                                      8
mehrauli  road                                                 8
malibu town                                                    8
sector 59                                                      8
sector 57                                                      8
palam vihar extension                                          8
sector 89 a                                                    8
sector 10a                                                     8
sector 43                                                      8
sector 11                                                      7
sector 26                                                      7
new colony                                                     7
mianwali colony                                                7
surat nagar 1                                                  7
sector 36 sohna                                                7
sector 51                                                      7
sector 58                                                      7
jacobpura                                                      6
ashok vihar                                                    6
sector 5                                                       6
rajiv nagar                                                    6
jyoti park                                                     6
sector 1                                                       6
sector 28                                                      5
subhash nagar                                                  5
dayanand colony                                                5
sector 9                                                       5
sector 2                                                       5
greenwood city                                                 5
arjun nagar                                                    5
sector 80                                                      5
sector 105                                                     5
manesar                                                        5
new palam vihar                                                5
sector 23a                                                     5
ansal plaza                                                    5
chakkarpur                                                     5
sector 30                                                      5
sushant lok phase 2                                            5
saraswati vihar                                                5
garhi harsaru                                                  4
adarsh nagar                                                   4
suncity                                                        4
sector 6                                                       4
krishna colony                                                 4
devilal colony                                                 4
sector 45                                                      4
bhim nagar                                                     4
sector 17                                                      4
sector 12a                                                     4
shivpuri                                                       4
new                                                            4
imt manesar                                                    4
valley view estate                                             4
sector 36                                                      4
sector 12                                                      4
dharam colony                                                  4
surya vihar                                                    4
sector 3a                                                      4
shivaji nagar                                                  4
baldev nagar                                                   4
ravi nagar                                                     4
vishnu garden                                                  4
bhondsi                                                        4
madanpuri                                                      4
patel nagar                                                    3
sector 17a                                                     3
a block sushant lok phase 1                                    3
sector 8                                                       3
sector 88b                                                     3
sector 27                                                      3
sector 15                                                      3
gandhi nagar                                                   3
shakti nagar                                                   3
maruti kunj                                                    3
sector 23                                                      3
sector 17b                                                     3
prem nagar                                                     3
mg road                                                        3
b block sushant lok phase 1                                    3
sector 110 a                                                   3
laxmi garden                                                   3
sector 73                                                      3
daulatabad                                                     2
faridabad road                                                 2
manohar nagar                                                  2
shankar vihar                                                  2
surat nagar                                                    2
surat nagar phase 2                                            2
bhawani enclave                                                2
sector-2 sohna                                                 2
hira nagar                                                     2
golf course ext road                                           2
acharya puri                                                   2
rajiv chowk                                                    2
sector 15 part 1                                               2
sector 15 part 2                                               2
block a surya vihar                                            2
sector 24                                                      2
sispal vihar                                                   2
mayfield garden                                                2
sector-11 sohna                                                2
west rajiv nagar                                               2
samaspur                                                       2
sector 32                                                      2
sheetla colony                                                 2
sector 21                                                      2
new palam vihar phase 2                                        2
ambience island                                                2
sushant lok                                                    2
rosewood                                                       2
pratap nagar                                                   2
sector 41                                                      2
nars                                                           2
mohan nagar                                                    2
new palam vihar phase 1                                        2
farukhnagar                                                    2
bissar                                                         2
new basti                                                      2
sohna  road                                                    2
iffco chowk                                                    2
lajpat nagar                                                   2
, delhi ncr                                                    2
shanti nagar                                                   2
golf course road                                               2
sultanpur                                                      1
vir nagar                                                      1
cyber city                                                     1
ram nagar                                                      1
saroop garden rajendra park                                    1
sector 42                                                      1
park view                                                      1
anand garden, sector-105                                       1
sector 5 chowk                                                 1
pataudi road                                                   1
near sector 1 market                                           1
devi lal colony gali no 12 gurgaon nr omkar public school      1
kanahi                                                         1
huda saraswati vihar                                           1
mahavir pura                                                   1
heritage city                                                  1
kheri                                                          1
gopal nagar, garhi ghasita, sonipat                            1
sector-7 hous                                                  1
new colony, sector 7                                           1
saraswati enclave                                              1
shivji park colony                                             1
sai kunj                                                       1
lucknow                                                        1
sector-5 sohna                                                 1
tekchand nagar                                                 1
g block dlf city phase 1                                       1
begampur khatola                                               1
garauli kalan                                                  1
near khandsa road                                              1
alipur                                                         1
om nagar                                                       1
block g sector-57                                              1
hsiidc plot sector 1 imt manesar                               1
bptp                                                           1
udyog vihar phase 1                                            1
sector-35 sohna                                                1
sector-5 sheetla colony                                        1
rattan garden                                                  1
ats marigold                                                   1
jacobpura near sadar bazar                                     1
sector 4 urban estate                                          1
sec 3 bhim vihar part 1 bhimgher kheri                         1
sector 13                                                      1
laxman vihar, railway road,                                    1
v block dlf phase 3                                            1
ashok vihar phase 3                                            1
laxmna vihar, phase 2                                          1
rajiv colony                                                   1
godrej aria , sector 79 ,                                      1
sector 9b                                                      1
near pataudi chowk                                             1
jat colony,fazilpur/taj nagar road                             1
south city                                                     1
new jyoti park                                                 1
sadar bazar                                                    1
part 3 sector 5                                                1
b1 block sector 57                                             1
ansal's palam vihar                                            1
near euro                                                      1
damdma                                                         1
bhimgarh kheri phase 3                                         1
dhankot                                                        1
block h ashok vihar phase iii extension                        1
mahalaxmi garden, rajendra place                               1
near nand hospital                                             1
old delhi road, opp sector-14                                  1
sector 37a                                                     1
sector 17c                                                     1
khandsa                                                        1
sector 37b                                                     1
nirvana country pocket h                                       1
civil l                                                        1
ashok vihar phase i                                            1
urban estate, sector 5                                         1
ravi nager basai road                                          1
naharpur rupa                                                  1
bhora kalan                                                    1
sector 21a faridabad                                           1
carterpuri village                                             1
hno 13 sagar enclave sura                                      1
Name: count, dtype: int64

In [18]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

In [19]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')

In [20]:
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')

In [21]:
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')

In [22]:
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [23]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [24]:
df['sector'].value_counts()

sector
sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 81                      90
sector 90                      90
sector 65                      90
sector 109                     88
sector 79                      80
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 50                      65
sector 107                     60
sector 108                     59
sector 56                      57
sector 95                      57
sector 89                      56
sector 48                      56
sector 2                       55
sector 70a                     54
sector 37c                     53
sector 70                      53
sector 43                      53
sector-33 sohna road           51
sector 84                      51
sector 26                      50
sector 67                      48
sector 49                      48
sector 28                      47
sector 66                      46
sector 103                     45
sector 113                     43
sector 25                      43
sector 61                      42
sector 82                      42
sector 7                       39
sector 106                     38
sector 4                       36
sector 99a                     32
sector 54                      31
sector 12                      30
sector 68                      30
sector 77                      29
sector 72                      29
sector 71                      27
sector 57                      24
sector 24                      24
sector 112                     24
sector 88a                     23
sector 105                     23
sector 33                      23
sector 14                      23
sector 67a                     22
sector 111                     22
sector 11                      21
sector 82a                     20
sector 22                      20
sector 3                       20
sector 47                      19
sector 78                      19
sector 63a                     18
gwal pahari                    18
sector 74                      18
sector 62                      17
sector 91                      17
sector 110                     16
sector 99                      16
sector 63                      15
sector 60                      15
sector 1 manesar               14
sector 76                      14
sector 53                      14
sector 55                      14
sector 52                      14
sector 6                       13
sector 46                      13
sector 9                       13
sector 36a                     13
sector 4 phase 2               13
sohna road road                12
sector 38                      12
sector 93                      12
sector 31                      12
sector 39                      12
sector 41                      11
sector 3 phase 3 extension     11
sector 9a                      11
sector 13                      10
sector 1a manesar              10
sector 3 phase 2                9
sector 45                       9
sector 95a                      9
manesar                         9
sector 40                       8
sector 10a                      8
sector 59                       8
c block sector 43               8
dwarka expressway               8
sector 23                       8
sector 89 a                     8
sector 17                       8
sector 2 extension              8
sector 8                        8
sector 58                       7
sector 51                       7
sector 36 sohna road            7
sector 1                        6
sector 21                       6
sector 5                        6
sector 30                       5
sector 80                       5
new sector 2                    5
sector 23a                      5
sector 3a                       4
sector 12a                      4
sector 36                       4
new                             4
sector 17b                      3
sector 17a                      3
sector 15                       3
a block sector 43               3
sector 88b                      3
sector 27                       3
patel nagar                     3
b block sector 43               3
sector 110 a                    3
sector 73                       3
maruti kunj                     3
Name: count, dtype: int64

In [25]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

C:\Users\ajjur\AppData\Local\Temp\ipykernel_21940\3954173571.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
C:\Users\ajjur\AppData\Local\Temp\ipykernel_21940\3954173571.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
C:\Users\ajjur\AppData\Local\Temp\ipykernel_21940\3954173571.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
C:\Users\ajjur\AppData\Local\Temp\ipykernel_21940\3954173571.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
C:\Users\ajjur\AppData\Local\Temp\ipykernel_21940\3954173571.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
C:\Users\ajjur\AppData\Local\Temp\ipykernel_21940\3954173571.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
C:\Users\ajjur\AppData\Local\Temp\ipykernel_21940\3954173571.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
C:\Users\ajjur\AppData\Local\Temp\ipykernel_21940\3954173571.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
C:\Users\ajjur\AppData\Local\Temp\ipykernel_21940\3954173571.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

In [26]:
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

C:\Users\ajjur\AppData\Local\Temp\ipykernel_21940\600812590.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
C:\Users\ajjur\AppData\Local\Temp\ipykernel_21940\600812590.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
C:\Users\ajjur\AppData\Local\Temp\ipykernel_21940\600812590.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
C:\Users\ajjur\AppData\Local\Temp\ipykernel_21940\600812590.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
C:\Users\ajjur\AppData\Local\Temp\ipykernel_21940\600812590.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
C:\Users\ajjur\AppData\Local\Temp\ipykernel_21940\600812590.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
C:\Users\ajjur\AppData\Local\Temp\ipykernel_21940\600812590.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
C:\Users\ajjur\AppData\Local\Temp\ipykernel_21940\600812590.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [27]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
711,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
2087,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
3338,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
3644,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN

In [28]:
df.loc[955,'sector'] = 'sector 37'
df.loc[2800,'sector'] = 'sector 92'
df.loc[2838,'sector'] = 'sector 90'
df.loc[2857,'sector'] = 'sector 76'

In [29]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1062,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2,2,2,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1652,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,1,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
1795,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,2,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
2111,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2,1,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."
3722,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [31]:
df.loc[[311,1072,1486,3040],'sector'] = 'sector 110'

In [32]:
df.shape

(3803, 21)

In [33]:
df.duplicated().sum()

np.int64(0)

In [34]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 90 Gurgaon,flat,shree vardhman flora,sector 90,0.85,4404.0,1930.0,Super Built up area 1930(179.3 sq.m.)Carpet ar...,3,4,3,"servant room,store room","305, Sector 90 Gurgaon, Gurgaon, Haryana",3.0,South-East,1 to 5 Year Old,"['IRIS Broadway Mall', 'Dwarka Expressway', 'S...",One of the best location of the society with g...,NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction5 out of..."
1,2 BHK Flat in Sohna,flat,gls arawali homes,sohna road,0.27,4600.0,587.0,Super Built up area 576(53.51 sq.m.),2,2,2,not available,"Sohna, Gurgaon, Haryana",5.0,NaN,0 to 1 Year Old,"['Huda City Centre', 'Golf Course Road', 'Delh...",Tower 13 floor 5th house no. 508. Freehold pro...,[],"['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Management4 out of 5', 'Green Area5 out of 5..."
2,2 Bedroom House for sale in Sector 70A Gurgaon,house,bptp pedestal,sector 70a,0.90,7582.0,1187.0,Carpet area: 1187 (110.28 sq.m.),2,2,3+,"servant room,others","123, Sector 70A Gurgaon, Gurgaon, Haryana",3.0,North-East,0 to 1 Year Old,"['Ninex Mall', 'Airia Mall', 'Meditree Market'...",This 2 bhk house for sale in sector 70a gurgao...,"['1 Exhaust Fan', '3 AC', '1 Modular Kitchen',...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Safety4 out of 5', ..."
3,4 BHK Flat in Sector-33 Sohna,flat,central park flower valley,sector 33,2.30,12777.0,1800.0,Carpet area: 1800 (167.23 sq.m.),4,4,3+,"pooja room,servant room","Sector-33 Sohna, Gurgaon, Haryana",5.0,North-East,0 to 1 Year Old,"['Golf Course Extension Rd', 'Rajiv Chowk - So...",9 sports academiesMulti-Cuisine restaurantKids...,"['4 Wardrobe', '4 Fan', '18 Light', '1 Chimney...","['Feng Shui / Vaastu Compliant', 'Security / F...",NaN
4,3 BHK Flat in Sector 92 Gurgaon,flat,sare crescent parc,sector 92,0.51,4080.0,1250.0,Super Built up area 1250(116.13 sq.m.),3,2,2,not available,"Sare, Sector 92 Gurgaon, Gurgaon, Haryana",2.0,North,1 to 5 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",Ready to move in keys in hand for visit feel f...,[],"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area4 out of 5', 'Construction4 out of..."

In [35]:
# features to drop -> property_name, address, description, rating
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [36]:
df.sample(5)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
617,flat,orchid petals,sector 49,2.38,11497.0,2070.0,Super Built up area 2070(192.31 sq.m.)Built Up...,3,4,3,study room,1.0,West,1 to 5 Year Old,"['Sapphire Mall', 'Omaxe City Centre', 'BigBaz...","['1 Fan', '1 Geyser', '1 Chimney', '1 Modular ...","['Feng Shui / Vaastu Compliant', 'Security / F..."
1662,flat,shree vardhman flora,sector 90,1.27,4951.0,2565.0,Super Built up area 2575(239.23 sq.m.)Carpet a...,4,5,2,"study room,servant room",9.0,North-East,0 to 1 Year Old,"['IRIS Broadway Mall', 'Dwarka Expressway', 'S...",NaN,"['Power Back-up', 'Intercom Facility', 'Lift(s..."
328,flat,beverley park 1,sector 43,8.44,16230.0,5200.0,Super Built up area 5200(483.1 sq.m.)Built Up ...,4,5,3,servant room,9.0,North-East,5 to 10 Year Old,"['Mg road metro station', 'Iffco chowk metro s...","['1 Water Purifier', '8 Fan', '1 Fridge', '1 E...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
192,flat,tulip violet,sector 69,1.70,8445.0,2013.0,Super Built up area 2010(186.74 sq.m.),4,4,2,not available,7.0,West,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...","['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Security / Fire Alarm', 'Power Back-up', 'Fe..."
2816,house,independent,sector 43,2.15,13030.0,1650.0,Built Up area: 1650 (153.29 sq.m.),1,1,0,not available,1.0,NaN,undefined,"['Huda city centre metro station', 'Iffco chow...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN

In [37]:
# feature engineering required -> areaWithType, additionalRoom, facing, agePossession, furnishDetails, features

In [38]:
df.duplicated().sum()

np.int64(122)

In [39]:
df.to_csv('../data/gurgaon_properties_cleaned_v1.csv',index=False)